{{- /*
Copyright 2024 New Vector Ltd
Copyright 2025-2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.wellKnownDelegation -}}
{{- if .enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- include "element-io.ess-library.ingress-service.annotations" (dict "root" $ "context" .ingress) | nindent 2 }}
  labels:
    {{- include "element-io.well-known-delegation-ingress.labels" (dict "root" $ "context" $.Values.haproxy) | nindent 4 }}
  name: {{ $.Release.Name }}-well-known
  namespace: {{ $.Release.Namespace }}
spec:
{{- include "element-io.ess-library.ingress-service.spec" (dict "root" $ "context" .ingress) | nindent 2 }}
  ports:
  - name: haproxy-wkd
    port: 8010
    targetPort: haproxy-wkd
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-haproxy"
{{- end -}}
{{- end -}}
