{{- /*
Copyright 2024-2025 New Vector Ltd
Copyright 2025-2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- with $.Values.matrixRTC -}}
{{- if .enabled -}}
{{- with .sfu -}}
{{- if and .enabled .exposedServices.rtcUdp.enabled (ne .exposedServices.rtcUdp.portType "HostPort") -}}
{{- $range_start := (.exposedServices.rtcUdp.portRange.startPort | int) -}}
{{- $range_end := (.exposedServices.rtcUdp.portRange.endPort | int) -}}
{{- $range_size := sub $range_end $range_start -}}
{{- $number_of_ranges := ((add ((div $range_size 250) | floor | int) 1) | int) -}}
{{- range $port_segment := until $number_of_ranges }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "element-io.matrix-rtc-sfu.labels" (dict "root" $ "context" (mustMergeOverwrite (dict "suffix" "-rtc") $.Values.matrixRTC.sfu)) | nindent 4 }}
  {{- with $.Values.matrixRTC.sfu.exposedServices.rtcUdp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $.Release.Name }}-matrix-rtc-sfu-udp-range-{{ $port_segment }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: {{ $.Values.matrixRTC.sfu.exposedServices.rtcUdp.portType }}
  {{- if hasKey $.Values.matrixRTC.sfu.exposedServices.rtcUdp "externalIPs" }}
  externalIPs: {{ $.Values.matrixRTC.sfu.exposedServices.rtcUdp.externalIPs | toYaml | nindent 4 }}
  {{- end }}
  ipFamilyPolicy: PreferDualStack
  internalTrafficPolicy: {{ $.Values.matrixRTC.sfu.exposedServices.rtcUdp.internalTrafficPolicy }}
  externalTrafficPolicy: {{ $.Values.matrixRTC.sfu.exposedServices.rtcUdp.externalTrafficPolicy }}
  ports:
{{- $segment_start := ((add $range_start (mul 250 $port_segment)) | int) }}
{{- $segment_end := ((min (add $range_end 1) (add $segment_start 250)) | int) }}
{{- range $port := untilStep $segment_start $segment_end 1 }}
  - name: rtc-udp-{{ $port }}
    port: {{ $port }}
    targetPort: {{ $port }}
    {{- with $.Values.matrixRTC.sfu.exposedServices.rtcUdp.portRange.nodePort }}
    nodePort: {{ tpl . (dict "context" (mustMergeOverwrite (dict "port" $port) ($.Values.matrixRTC.sfu.exposedServices.rtcUdp)) "root" $)  }}
    {{- end }}
    protocol: UDP
{{- end }}
  selector:
    app.kubernetes.io/instance: "{{ $.Release.Name }}-matrix-rtc-sfu"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
