{{- /*
Copyright 2026 Element Creations Ltd

SPDX-License-Identifier: AGPL-3.0-only
*/ -}}

{{- if or (and $.Values.synapse.enabled ((include "element-io.synapse.enabledWorkers" (dict "root" $)) | fromJson))
          $.Values.hookshot.enabled -}}
{{- with $.Values.redis -}}
apiVersion: apps/v1
kind: Deployment
metadata:
{{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "element-io.redis.labels" (dict "root" $ "context" (dict "image" .image "labels" .labels)) | nindent 4 }}
    k8s.element.io/redis-config-hash: "{{ include "element-io.redis.configmap-data" (dict "root" $ "context" .) | sha1sum }}"
  name: {{ $.Release.Name }}-redis
  namespace: {{ $.Release.Namespace }}
spec:
  {{ include "element-io.ess-library.workloads.commonSpec" (dict "root" $ "context" (dict "nameSuffix" "redis" "kind" "Deployment" "componentValues" .)) | nindent 2 }}
  template:
    metadata:
      labels:
        {{- include "element-io.redis.labels" (dict "root" $ "context" (dict "image" .image "labels" .labels "withChartVersion" false)) | nindent 8 }}
        k8s.element.io/redis-config-hash: "{{ include "element-io.redis.configmap-data" (dict "root" $ "context" .) | sha1sum }}"
{{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
{{- end }}
    spec:
{{- include "element-io.ess-library.pods.commonSpec" (dict "root" $ "context" (dict "componentValues" . "instanceSuffix" "redis" "deployment" true)) | nindent 6 }}
{{- with .extraInitContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
{{- end }}
      containers:
      - name: redis
        args:
        - "/config/redis.conf"
        {{- include "element-io.ess-library.pods.image" (dict "root" $ "context" .image) | nindent 8 }}
{{- with .containersSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
{{- end }}
        {{- include "element-io.ess-library.pods.env" (dict "root" $ "context" (dict "componentValues" . "componentName" "redis")) | nindent 8 }}
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        startupProbe: {{- include "element-io.ess-library.pods.probe" .startupProbe | nindent 10 }}
          tcpSocket:
            port: redis
        livenessProbe: {{- include "element-io.ess-library.pods.probe" .livenessProbe | nindent 10 }}
          tcpSocket:
            port: redis
        readinessProbe: {{- include "element-io.ess-library.pods.probe" .readinessProbe | nindent 10 }}
          exec:
            command:
            - redis-cli
            - ping
{{- with .resources }}
        resources:
          {{- toYaml . | nindent 10 }}
{{- end }}
        volumeMounts:
        - mountPath: /config/redis.conf
          name: config
          readOnly: true
          subPath: redis.conf
{{- range .extraVolumeMounts }}
        - {{ (. | toYaml) | nindent 10 }}
{{- end }}
      restartPolicy: Always
      volumes:
      - configMap:
          name: "{{ $.Release.Name }}-redis"
          defaultMode: 420
        name: config
{{- range .extraVolumes }}
      - {{- (tpl (. | toYaml) $) | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
