# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:

  passkey:
    value: |
      CHANGEME
      -----BEGIN PRIVATE KEY-----
      MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQDLtjXE9gRU9GVE
      2Kt8VQORnOOlNlPvTwosXeSvJKl0llRW3ajDqpfbHfG2BOTvnHEqfO5KQGXCwBmx
      3a0sbQ0x4upx47vOpX+zpOaF3gor
      -----END PRIVATE KEY-----

  appserviceRegistration:
    value: |
      rate_limited: false
      namespaces:
        users:
          - regex: "@_github_.*:{{ $.Release.Name }}"
            exclusive: true
      id: hookshot
      hs_token: "CHANGEME-cie9nehee2ohSahloh3Ahquii3ningai"
      as_token: "CHANGEME-ushi5ieMaebooJahquaechucha7Owua2"
      url: "http://hookshot:9993"
      sender_localpart: "hookshot"
