# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:
  additional:
    example-value:
      configSecret: "{{ $.Release.Name }}-hookshot-external"
      configSecretKey: config