# Copyright 2025 New Vector Ltd
# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

hookshot:

  passkey:
    secret: "{{ $.Release.Name }}-hookshot-external-passkey"
    secretKey: passfile

  appserviceRegistration:
    secret: "{{ $.Release.Name }}-hookshot-external-registration"
    secretKey: registration.yaml

