# Copyright 2025-2026 Element Creations Ltd
#
# SPDX-License-Identifier: AGPL-3.0-only

matrixRTC:
  sfu:
    exposedServices:
      turnTLS:
        enabled: true
        tlsSecret: "{{ $.Release.Name }}-turn-tls"
